import type {
	DoorsPageContent,
	AboutPageContent,
	BeforeAfterSlide,
	ContactsPageContent,
	HomeAboutContent,
	HomeBeforeAfterBannerContent,
	HomeContactContent,
	HomeNumbersContent,
	HomePortfolioContent,
	HomePricingContent,
	HomeProcessContent,
	HomeServicesContent,
	HeroContent,
	PortfolioPageContent,
	ReviewsPageContent,
	ServiceDetail,
	ServicesPageContent,
	SiteSettingsContent,
	PageSeo,
	SiteMetadataPageKey,
	ServicePageHeroContent,
} from './types'

export const DEFAULT_HERO: HeroContent = {
	isShowed: true,
	locationLabel: '',
	titleLine1: '',
	description: '',
	primaryCtaLabel: '',
	secondaryCtaLabel: '',
	formTitle: '',
	formSubtext: '',
	formNote: '',
	backgroundImageUrl: '',
	backgroundImageAlt: null,
}

export const DEFAULT_SITE_SETTINGS: SiteSettingsContent = {
	testimonialsIsShowed: true,
	testimonialsBackgroundUrl: '',
	testimonialsBackgroundAlt: null,
	footerDescription: '',
	phone: '',
	phoneHours: '',
	officeWeekdayHours: '',
	email: '',
	emailNote: '',
	notificationEmail: '',
	whatsapp: '',
	whatsappNote: '',
	serviceArea: '',
	serviceAreaNote: '',
	instagramUrl: '',
	facebookUrl: '',
	houzzUrl: '',
	homestarsUrl: '',
}

export const DEFAULT_PAGE_SEO: Record<SiteMetadataPageKey, PageSeo> = {
	home: {
		title: 'Formo Renovations — Design & Renovation Solutions',
		description:
			'Premium renovation and interior finishing solutions for homes across Victoria and Vancouver Island, BC.',
		ogImageUrl: null,
		jsonLd: '',
	},
	aboutUs: {
		title: 'About Formo Renovations — Our Story, Team & Values',
		description:
			'Learn the story behind Formo Renovations — our team, values, and commitment to quality craftsmanship across Victoria and Vancouver Island, BC since 2016.',
		ogImageUrl: null,
		jsonLd: '',
	},
	services: {
		title: 'Our Services — Formo Renovations',
		description:
			'Full-range renovation and interior finishing services for Victoria and Vancouver Island — bathrooms, kitchens, flooring, full home renovations, and more.',
		ogImageUrl: null,
		jsonLd: '',
	},
	portfolio: {
		title: 'Renovation Portfolio — Formo Projects in Victoria, BC',
		description:
			'Browse our completed renovation projects across Victoria and Vancouver Island, BC — kitchens, bathrooms, living rooms, and full apartment transformations.',
		ogImageUrl: null,
		jsonLd: '',
	},
	reviews: {
		title: 'Client Reviews — Formo Renovations',
		description:
			'Read genuine client reviews from homeowners across Victoria and Vancouver Island, BC. Share your own experience with Formo Renovations.',
		ogImageUrl: null,
		jsonLd: '',
	},
	contacts: {
		title: 'Contact Us — Formo Renovations',
		description:
			'Get in touch with Formo Renovations. Free on-site consultations across Victoria and Vancouver Island, BC. Call, email, or fill in the form.',
		ogImageUrl: null,
		jsonLd: '',
	},
}

export const DEFAULT_HOME_NUMBERS: HomeNumbersContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	stats: [],
}

export const DEFAULT_HOME_SERVICES: HomeServicesContent = {
	isShowed: true,
	eyebrow: '',
	title: '',
	titleAccent: '',
	cards: [],
}

export const DEFAULT_HOME_ABOUT: HomeAboutContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	heroDescription: '',
	heroCtaLabel: '',
	heroCtaLink: '',
	heroImageUrl: '',
	rows: [],
}

export const DEFAULT_HOME_PORTFOLIO: HomePortfolioContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	description: '',
	ctaLabel: '',
	ctaLink: '',
	heroImageUrl: '',
	projects: [],
}

export const DEFAULT_HOME_PROCESS: HomeProcessContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	description: '',
	ctaLabel: '',
	heroImageUrl: '',
	steps: [],
}

export const DEFAULT_HOME_PRICING: HomePricingContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	heroDescription: '',
	heroCtaLabel: '',
	heroImageUrl: '',
	introTitle: '',
	introText: '',
	factors: [],
	ctaLabel: '',
	ctaTitle: '',
	ctaSubtext: '',
	ctaPrimaryLabel: '',
	ctaSecondaryLabel: '',
}

export const DEFAULT_HOME_CONTACT: HomeContactContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	lead: '',
	ctaLabel: '',
	formTitle: '',
	formSubtext: '',
	photoUrl: '',
	photoAlt: '',
}

export const DEFAULT_HOME_BEFORE_AFTER_BANNER: HomeBeforeAfterBannerContent = {
	isShowed: true,
	eyebrow: '',
	headline: '',
	headlineEmphasis: '',
	description: '',
	ctaLabel: '',
	heroBackgroundUrl: '',
}

export const DEFAULT_BEFORE_AFTER: BeforeAfterSlide[] = []

export const DEFAULT_PORTFOLIO_PAGE: PortfolioPageContent = {
	locationLabel: '',
	titleBefore: '',
	titleEmphasis: '',
	description: '',
	primaryCtaLabel: '',
	primaryCtaLink: '',
	secondaryCtaLabel: '',
	secondaryCtaLink: '',
	heroImageUrl: '',
	stats: [],
}

export const DEFAULT_SERVICES_PAGE: ServicesPageContent = {
	heroIsShowed: true,
	listIsShowed: true,
	processIsShowed: true,
	pricingIsShowed: true,
	faqIsShowed: true,
	locationLabel: '',
	titleBefore: '',
	titleEmphasis: '',
	description: '',
	primaryCtaLabel: '',
	primaryCtaLink: '',
	secondaryCtaLabel: '',
	secondaryCtaLink: '',
	heroImageUrl: '',
	processHeroBackgroundUrl: '',
	processEyebrow: '',
	processHeadline: '',
	processHeadlineEmphasis: '',
	processDescription: '',
	processSteps: [],
	pricingEyebrow: '',
	pricingHeadline: '',
	pricingHeadlineEmphasis: '',
	pricingBody: '',
	pricingCards: [],
	faqEyebrow: '',
	faqTitle: '',
	faqTitleEmphasis: '',
	faqSub: '',
	faqItems: [],
}

export const DEFAULT_ABOUT_PAGE: AboutPageContent = {
	heroIsShowed: true,
	founderCardIsShowed: false,
	whoIsShowed: true,
	storyIsShowed: false,
	valuesIsShowed: true,
	teamIsShowed: false,
	whyIsShowed: true,
	certIsShowed: true,
	locationLabel: '',
	titleBefore: '',
	titleEmphasis: '',
	description: '',
	primaryCtaLabel: '',
	primaryCtaLink: '',
	secondaryCtaLabel: '',
	secondaryCtaLink: '',
	heroImageUrl: '',
	valuesHeroBackgroundUrl: '',
	whyBannerBackgroundUrl: '',
	founderInitial: '',
	founderName: '',
	founderRole: '',
	founderQuote: '',
	founderStats: [],
	whoEyebrow: '',
	whoHeadline: '',
	whoHeadlineEmphasis: '',
	whoLead: '',
	whoBody: [],
	whoPills: [],
	whoCtaLabel: '',
	whoCtaLink: '',
	storyEyebrow: '',
	storyHeadline: '',
	storyHeadlineEmphasis: '',
	storyLead: '',
	timeline: [],
	valuesEyebrow: '',
	valuesHeadline: '',
	valuesHeadlineEmphasis: '',
	valuesDescription: '',
	valueCards: [],
	teamEyebrow: '',
	teamHeadline: '',
	teamHeadlineEmphasis: '',
	teamDescription: '',
	teamMembers: [],
	whyEyebrow: '',
	whyBannerHeadline: '',
	whyBannerHeadlineEmphasis: '',
	whyBannerDescription: '',
	whyRows: [],
	certEyebrow: '',
	certHeadline: '',
	certHeadlineEmphasis: '',
	certDescription: '',
	certBadges: [],
	guaranteeCards: [],
}

export const DEFAULT_REVIEWS_PAGE: ReviewsPageContent = {
	heroImageUrl: '',
}

export const DEFAULT_CONTACTS_PAGE: ContactsPageContent = {
	eyebrow: '',
	titleBefore: '',
	titleEmphasis: '',
	description: '',
	heroImageUrl: '',
	formEyebrow: '',
	formTitleBefore: '',
	formTitleEmphasis: '',
	formSubtext: '',
}

export const DEFAULT_DOORS_PAGE: DoorsPageContent = {
	seo: {
		title: 'Formo | Door Installation & Repair in Victoria, BC',
		description:
			'Formo door installation and repair in Victoria, BC. Explore entry, patio, interior, garage, commercial and industrial door services and request an estimate.',
		ogImageUrl: null,
		jsonLd: '',
	},
	heroEyebrow: 'Door installation & repair · Victoria, BC',
	heroTitleBefore: 'A better door.',
	heroTitleEmphasis: 'A better welcome.',
	heroSubtitle: 'Thoughtfully chosen. Carefully installed.',
	heroPrimaryCtaLabel: 'Get a free estimate',
	heroSecondaryCtaLabel: 'Explore doors',
	heroImageAlt: 'Architectural concept: a modern West Coast home with cedar siding and a charcoal entry door',
	heroCaption: 'Made for the way you live.',
	stripItems: ['New doors', 'Replacements', 'Repairs'],
	stripLocation: 'Homes & businesses in Victoria, BC',
	introEyebrow: 'Meet Formo',
	introTitleBefore: 'Good design.',
	introTitleEmphasis: 'Down to the details.',
	introBody:
		'Formo Renovations is a Victoria-based renovation and finishing company, bringing experience from Europe and Canada to homes across Vancouver Island. Our door services bring that same attention to the details you see and use every day.',
	introLinkLabel: 'About Formo Renovations',
	introLinkHref: '/about-us/',
	availabilityLabel: 'Here when you need us.',
	estimateEyebrow: 'Your project starts here',
	estimateTitle: 'Let’s talk doors.',
	estimateLead: 'A few details. A clear next step.',
	estimateSubmitLabel: 'Request a free estimate',
	estimatePrivacy: 'By submitting, you agree to be contacted about your request.',
	residentialEyebrow: 'For your home',
	residentialTitleBefore: 'Make yourself',
	residentialTitleEmphasis: 'at home.',
	residentialLead: 'New installations and replacements.\nFrom the front step to the back garden.',
	catalogResidentialLabel: 'Residential',
	catalogCommercialLabel: 'Commercial & industrial',
	catalogRepairsLabel: 'Door repairs',
	residentialWideAlt: 'Sliding glass patio doors connecting a living room to a leafy garden',
	residentialWideCaption: 'Open up\nthe possibilities.',
	residentialCards: [
		{title: 'Front Entry Door', description: 'Make a welcoming first impression with a front entrance that suits your home.', imageKey: 'front-entry'},
		{title: 'Patio Door', description: 'Connect your living space and garden with sliding, French or bi-fold door options.', imageKey: 'patio-door'},
		{title: 'Sliding Closet Door', description: 'Make everyday storage easier with doors chosen to fit your room and opening.', imageKey: 'closet-door'},
		{title: 'Interior Door', description: 'Bring a consistent look to bedrooms, hallways and the spaces in between.', imageKey: 'interior-door'},
		{title: 'Door Glass Insert', description: 'Refresh the look of an existing entrance with a decorative or privacy glass insert.', imageKey: 'glass-insert'},
		{title: 'Garage Door', description: 'Explore replacement and new installation options for your garage entrance.', imageKey: 'garage-door'},
	],
	commercialEyebrow: 'For your business',
	commercialTitleBefore: 'A better entrance.',
	commercialTitleEmphasis: 'For every business.',
	commercialLead:
		'Entrances that welcome customers. Doors that work with your space. Explore installation options for commercial and industrial properties in Victoria.',
	commercialCtaLabel: 'Discuss your project',
	commercialCtaService: 'Commercial Door',
	commercialImageAlt: 'Contemporary commercial glass entry doors in dark aluminum frames',
	commercialCards: [
		{title: 'Commercial Door', description: 'Door installation and replacement for offices, shops and other commercial spaces.', imageKey: 'commercial-door'},
		{title: 'Commercial Glass Entry Door', description: 'Create a bright, welcoming entrance with commercial glass and aluminum doors.', imageKey: 'storefront-door'},
		{title: 'Commercial Fire-Rated Door', description: 'Discuss the specified fire rating, hardware and requirements for your project.', imageKey: 'fire-rated-door'},
		{title: 'Industrial Door', description: 'Explore door options suited to your building, access needs and day-to-day use.', imageKey: 'industrial-door'},
	],
	repairsEyebrow: 'Door repairs',
	repairsTitleBefore: 'Not quite right?',
	repairsTitleEmphasis: 'Let’s fix that.',
	repairsLead: 'Sticking, scraping, damaged or difficult to close?\nChoose your door type to start a repair enquiry.',
	repairCards: [
		{title: 'Entry Door Repair', description: 'Help with sticking doors, worn hinges, handles and everyday opening problems.', imageKey: 'front-entry'},
		{title: 'Exterior Door Repair', description: 'Discuss drafts, weather seals, alignment and damage around your outside entrance.', imageKey: 'glass-insert'},
		{title: 'Interior Door Repair', description: 'Get bedroom, hallway and other interior doors moving and closing smoothly again.', imageKey: 'interior-door'},
		{title: 'Patio Door Repair', description: 'Ask about difficult sliding, damaged tracks, rollers, locks and weather sealing.', imageKey: 'patio-door'},
		{title: 'Commercial Door Repair', description: 'Help with closers, hinges, hardware and daily access to your business.', imageKey: 'commercial-door'},
		{title: 'Storefront Door Repair', description: 'Discuss alignment, handles and closing problems with your glass storefront entrance.', imageKey: 'storefront-door'},
		{title: 'Residential Garage Door Repair', description: 'Tell us about noise, movement, hardware or opening issues with your garage door.', imageKey: 'garage-door'},
		{title: 'Commercial Garage Door Repair', description: 'Explore repair options for overhead doors serving a workshop or commercial property.', imageKey: 'industrial-door'},
	],
	emergencyEyebrow: 'Need a hand?',
	emergencyTitle: 'Ask about emergency garage door repair.',
	emergencyLead: 'Tell us what happened and confirm the next available appointment.',
	emergencyCtaLabel: 'Request assistance',
	emergencyService: 'Emergency Garage Door Repair',
	processEyebrow: 'The Formo approach',
	processTitleBefore: 'A clear process.',
	processTitleEmphasis: 'A considered finish.',
	processLead: 'Renovation experience.\nAttention to every door.',
	processSteps: [
		{title: 'Consultation & assessment', description: 'Talk through your project, then assess the opening, measurements and scope on site.'},
		{title: 'A clear, written estimate', description: 'Review materials, labour and timing before agreeing on the work and signing a contract.'},
		{title: 'Installation & quality checks', description: 'Coordinate the work, check the details and finish with a walkthrough of the completed project.'},
	],
	proofStats: [
		{value: '10+', label: 'Years of renovation experience'},
		{value: '150+', label: 'Renovation projects completed'},
		{value: 'Victoria &\nVancouver Island', label: 'Our home. Our service area.'},
	],
	proofLinkLabel: 'Meet our renovation clients',
	proofLinkHref: '/reviews/',
}

export const DEFAULT_SERVICE_PAGE_HERO: ServicePageHeroContent = {
	isShowed: true,
	locationLabel: '',
	primaryCtaLabel: '',
	primaryCtaLink: '#contact',
	secondaryCtaLabel: '',
	secondaryCtaLink: '/services/',
}

export const DEFAULT_SERVICES: ServiceDetail[] = []
